window.KIRA_LEGAL_CONFIG = {
  checkoutEnabled: false,
  legalEntityName: "",
  tradingName: "Kira Engineer Hub",
  registrationNumber: "",
  registrationCountry: "",
  registeredAddress: "",
  supportEmail: "KE@kiraengineerhub.com",
  supportTelegram: "https://t.me/KIRAENGINEER",
  privacyContact: "KE@kiraengineerhub.com",
  complaintsEmail: "KE@kiraengineerhub.com",
  governingLaw: "",
  effectiveDate: "4 July 2026",
  cancellationDeadline: "Before the next renewal date",
  refundRequestDeadline: "As soon as possible after the billing issue or access-delivery issue is identified",
  complaintAcknowledgementTarget: "Within 7 business days where practical",
  complaintResponseTarget: "Within 30 business days where practical",
  termsVersion: "2026.07",
  privacyVersion: "2026.07",
  riskDisclosureVersion: "2026.07",
  refundPolicyVersion: "2026.07"
};
