window.KIRA_SITE_CONFIG = {
  companyName: "Kira Engineer Hub",
  websiteUrl: "https://www.kiraengineerhub.com",
  supportEmail: "info@kiraengineer.com",
  telegramUrl: "https://t.me/KiraTradingCommunity",
  instagramPrimary: "https://www.instagram.com/kira.engineer/",
  instagramTrading: "https://www.instagram.com/kira.tradingc/",
  monthlyMembershipPrice: 70,
  threeMonthMembershipPrice: 189,
  currency: "USD",
  earlyBirdCutoffDate: "2026-07-01T00:00:00+04:00",
  earlyBirdDiscountRate: 20,
  affiliateCommissionRate: 20,
  affiliateCommissionDuration: "first 90 days",
  affiliateCookieWindow: "30 days",
  affiliateValidationPeriod: "30 days",
  affiliateMinimumPayout: 50,
  legalLastUpdated: "July 2026",
  governingJurisdiction: "[GOVERNING JURISDICTION TO BE CONFIRMED]",
  complaintResponseTime: "[COMPLAINT RESPONSE TIME TO BE CONFIRMED]",
  refundWindow: "OWNER DECISION REQUIRED"
};
