window.KIRA_SITE_CONFIG = {
  companyName: "Kira Engineer Hub",
  websiteUrl: "https://www.kiraengineerhub.com",
  supportEmail: "KE@kiraengineerhub.com",
  telegramUrl: "https://t.me/KiraTradingCommunity",
  instagramPrimary: "https://www.instagram.com/kira.engineer/",
  instagramTrading: "https://www.instagram.com/kira.tradingc/",
  monthlyMembershipPrice: 50,
  threeMonthMembershipPrice: 135,
  currency: "USD",
  earlyBirdCutoffDate: "2026-07-01T00:00:00+04:00",
  earlyBirdDiscountRate: 20,
  affiliateCommissionRate: 20,
  affiliateCommissionDuration: "first 90 days",
  affiliateCookieWindow: "30 days",
  affiliateValidationPeriod: "30 days",
  affiliateMinimumPayout: 50,
  legalLastUpdated: "July 2026",
  governingJurisdiction: "To be finalized before paid checkout launches",
  complaintResponseTime: "Reasonable timeframe after complete information is received",
  refundWindow: "Defined in the published refund policy before paid checkout launches"
};
